# Generated by Django 2.0.7 on 2018-08-30 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180830_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authfacebook',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_facebook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authgithub',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_github', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authgoogle',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_google', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authlinkedin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_linkedin', to=settings.AUTH_USER_MODEL),
        ),
    ]
